### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by Itay-Tsabary-Starkware** [ejoffe/spr#276]
Will it be possible to change the tool such that it triggers the github checks only for modified commits?

Example:
Say I have commits 1 <- 2 <- 3 which were already submitted (using `git spr update`).

Then I make edits to commits 2 and 3 (using interactive rebasing), resulting in:
1 <- 2' <- 3' 

Currently, running `git spr update` re-triggers github checks for commit 1 just as well, though it hasn't changed.

Is there a way to disable this redundancy?

Much appreciated,
Itay

p.s.,
Loving this tool :-)

**Comment by ejoffe** [comment]
Hi Itay, 

My guess is that this is due to the rebase on origin. If there are new changes from upstream all the commits in the stack will end up re-triggering github checks. 
If this is the case, we can add a flag such as `git spr update --norebase` which will not pull in the latest changes, in this case I think only the commits in your stack starting from the one you updated will trigger the checks. 
Can you check if this is the case for you? If you edit commit 2, and no one else in the repository made changes, will commit 1 check get triggered?

Eitan

**Comment by Itay-Tsabary-Starkware** [comment]
Hi,

The repo I'm working with is frequently updated and our github checks take a while, I doubt I'd manage to squeeze in an uninterrupted update like that.

I don't really mind about the first commit being "outdated" w.r.t. to the current rebased origin -- this already happens since time passes between the checks and the actual merge.

The suggested flag seems like a great idea -- can this work based on the commit ids?
Something in the sort of:
1. Maintain a list of commit ids of the prs in the last `update` (or `merge`)
2. When a new `update` is invoked, only triger the githut checks for prs with different commit ids

Thanks (and hag sameh),
Itay

**Comment by ejoffe** [comment]
You can now run 'git spr update --no-rebase` or `git spr update -nr`. 
Also there is a configuration in the user config to disable rebase by default.
Thank you @adambenhassen for adding this flag!
