### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by hansbogert** [ejoffe/spr#295]
Will SPR be a Github only tool? Or, in the current developers' opinions, is SPR well suited to be extended for other code forges, like Gitlab?

**Comment by ejoffe** [comment]
Currently spr only works with the GitHub api. 
It looks like GitLab also has a graphql api, the api interface is mocked out in the code, so it should be possible to add a GitLab implementation without needed to change the core application. 
Someone using GitLab would have to implement this interface in order to add support for GitLab.

**Comment by hansbogert** [comment]
Just what I wanted to know! Thanks.
