### ISSUE TITLE
Allow using other people's commits as base

### ISSUE THREAD

**Issue by GregoRCodi** [ejoffe/spr#61]
Hey :slightly_smiling_face: 

I wanted to use another person's commit (not merged to `master` yet) as a base. The commits were as so:
* `master`
* `commit-from-colleague` (has an open PR using `git spr`)
* `my-commit <- HEAD` (no PR yet)

After executing `git spr update`, `spr` created 2 PRs - one for my commit, but another one for `commit-from-colleague` even though that commit already had a PR.

Can we detect such situations and then use an existing branch/PR as a base instead of recreating the PR as-if it was my own?

**Comment by ejoffe** [comment]
Currently pull requests a keyed by a tuple of (username, local branch, commit-id). 
Technically the commit-id is unique and so we could key by just that, and I think in that case you can have multiple people working together on a stack of commits. This does make it more complicated and might bring up interesting edge cases that need to be thought out and tested.

**Comment by ejoffe** [comment]
This requires more thought on how to do it right, I'm worried about cases of multiple writers to a single commit-id, where there could be cases that one person overwrites another persons changes. I'm going to keep this in the back of my mind, but for now on the back burner. If you have good ideas for this, feel free to discuss them here.

**Comment by schreter** [comment]
> This requires more thought on how to do it right, I'm worried about cases of multiple writers to a single commit-id, where there could be cases that one person overwrites another persons changes

That's exactly the problem/feature we had with Gerrit. There, the changes are keyed on "Change-Id" header in the commit message and pushing to the same remote branch would overwrite changes. Pushing to a different remote branch, however, was fine - the change ID was used to track cherry-picks across the version branches. In GitHub speak, that would key the PR to (tracking_branch, commit_id) instead of (username, local branch, commit_id).

So maybe it's not that big of a problem after all - especially if the rebase part on `spr update` would be optional (it seems to always rebase as of now) and thus the git commit wouldn't change.

**Comment by ejoffe** [comment]
You can sort of do this now with the 'git spr sync' feature. 
Although this is really meant for moving your own stack and should be careful if using it to interact between two coders.
